#!/bin/bash
# Apply mobile login fix to Supabase database

echo "=================================================="
echo "Mobile App Login Fix - Database Deployment"
echo "=================================================="
echo ""
echo "This script will guide you through applying the fix."
echo ""
echo "OPTION 1: Supabase Dashboard (Recommended)"
echo "-------------------------------------------"
echo "1. Open: https://supabase.com/dashboard/project/anlivujgkjmajkcgbaxw/sql"
echo "2. Click 'New Query'"
echo "3. Copy the content from: supabase/migrations/20260106000001_fix_mobile_login.sql"
echo "4. Paste into SQL Editor and click 'Run'"
echo ""
echo "OPTION 2: Run via psql (if you have direct access)"
echo "-------------------------------------------"
echo "psql postgresql://[connection-string] < supabase/migrations/20260106000001_fix_mobile_login.sql"
echo ""
echo "After running the SQL migration, rebuild the Android app:"
echo "cd mobile/android/EventNexusLiveMap && ./gradlew clean assembleDebug"
echo ""
echo "See docs/MOBILE_LOGIN_FIX_DEPLOYMENT.md for full instructions"
echo "=================================================="
