#!/bin/bash
# Quick test script for Facebook Page token OAuth fix

echo "======================================"
echo "Facebook Page Token Fix - Test Guide"
echo "======================================"
echo ""

echo "STEP 1: Update OAuth Scopes in Database"
echo "---------------------------------------"
echo "Run this in Supabase SQL Editor:"
echo ""
cat sql/update_oauth_scope_with_pages_list.sql
echo ""
echo "Press Enter when done..."
read

echo ""
echo "STEP 2: Disconnect Existing Connections"
echo "---------------------------------------"
echo "1. Go to Admin Panel → Social Media Manager"
echo "2. Click disconnect on existing Facebook/Instagram"
echo "3. Confirm disconnection"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "STEP 3: Reconnect Facebook"
echo "---------------------------------------"
echo "1. Click 'Connect Facebook' button"
echo "2. OAuth popup opens"
echo "3. ⚠️  IMPORTANT: Select specific Pages you want to use"
echo "4. Grant ALL requested permissions"
echo "5. Check browser console for logs"
echo ""
echo "Expected console output:"
echo "  🔄 Step 1: Exchanging for long-lived user token..."
echo "  ✅ Got long-lived user token (expires in X seconds)"
echo "  🔄 Step 2: Fetching Facebook Pages..."
echo "  📄 Facebook Pages response: { hasData: true, pageCount: 1 }"
echo "  ✅ Using Facebook Page: { id: 'XXX', name: 'YYY' }"
echo "  🔄 Step 3: Verifying Page token..."
echo "  ✅ Page token verified successfully"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "STEP 4: Test Facebook Posting"
echo "---------------------------------------"
echo "1. Create or select a campaign"
echo "2. Click 'Post to Facebook'"
echo "3. Check console logs:"
echo "   📘 Starting Facebook post..."
echo "   ✅ Posted to Facebook: POST_ID"
echo "   ✅ Database updated successfully"
echo ""
echo "4. Verify in database:"
echo "   SELECT * FROM user_campaigns WHERE facebook_posted = true ORDER BY created_at DESC LIMIT 1;"
echo "   SELECT * FROM social_media_posts WHERE platform = 'facebook' ORDER BY posted_at DESC LIMIT 1;"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "STEP 5: Test Instagram Posting"
echo "---------------------------------------"
echo "1. Click 'Connect Instagram' if not connected"
echo "2. Select Page with Instagram Business Account"
echo "3. Try posting to Instagram"
echo "4. Expected console:"
echo "   📸 Starting Instagram post..."
echo "   ✅ Instagram container created: CONTAINER_ID"
echo "   ✅ Posted to Instagram: POST_ID"
echo "   ✅ Database updated successfully"
echo ""
echo "Press Enter when done..."
read

echo ""
echo "======================================"
echo "Test Complete!"
echo "======================================"
echo ""
echo "If any step failed, check:"
echo "1. Facebook Page exists and you're admin"
echo "2. OAuth permissions were fully granted"
echo "3. Instagram is Business Account (for Instagram)"
echo "4. Instagram connected to Facebook Page"
echo "5. Console logs for detailed error messages"
echo ""
echo "Documentation:"
echo "- English: docs/PAGE_TOKEN_FIX_SUMMARY.md"
echo "- Estonian: docs/PAGE_TOKEN_AUTOMAATNE_FIX_ET.md"
echo ""
