-- ============================================================
-- Fix Campaign Performance Table Column Names
-- ============================================================
-- Issue: Code expects 'total_revenue' but table has 'revenue'
-- Solution: Rename column for consistency
-- ============================================================

-- Check if campaign_performance table exists
DO $$ 
BEGIN
  -- Rename revenue to total_revenue if column exists
  IF EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'campaign_performance' 
      AND column_name = 'revenue'
  ) THEN
    ALTER TABLE public.campaign_performance 
    RENAME COLUMN revenue TO total_revenue;
    
    RAISE NOTICE 'Renamed revenue to total_revenue in campaign_performance';
  END IF;
  
  -- Ensure total_revenue column exists
  IF NOT EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'campaign_performance' 
      AND column_name = 'total_revenue'
  ) THEN
    ALTER TABLE public.campaign_performance 
    ADD COLUMN total_revenue DECIMAL(10,2) DEFAULT 0.00;
    
    RAISE NOTICE 'Added total_revenue column to campaign_performance';
  END IF;
END $$;

-- Add comment
COMMENT ON COLUMN public.campaign_performance.total_revenue IS 'Total revenue generated by campaign';
